/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zim
 */
public class BillDetailsAdmin extends javax.swing.JFrame {

   int positionX = 0, positionY=0;


    public BillDetailsAdmin() {
        initComponents();
        
        bmonth.add("January");
        bmonth.add("February");
        bmonth.add("March");
        bmonth.add("April");
        bmonth.add("May");
        bmonth.add("June");
        bmonth.add("July");
        bmonth.add("August");
        bmonth.add("September");
        bmonth.add("October");
        bmonth.add("November");
        bmonth.add("December");
        
        umonth.add("January");
        umonth.add("February");
        umonth.add("March");
        umonth.add("April");
        umonth.add("May");
        umonth.add("June");
        umonth.add("July");
        umonth.add("August");
        umonth.add("September");
        umonth.add("October");
        umonth.add("November");
        umonth.add("December");
        
        tmonth.add("January");
        tmonth.add("February");
        tmonth.add("March");
        tmonth.add("April");
        tmonth.add("May");
        tmonth.add("June");
        tmonth.add("July");
        tmonth.add("August");
        tmonth.add("September");
        tmonth.add("October");
        tmonth.add("November");
        tmonth.add("December");
        
        amonth.add("Full Year");
        amonth.add("January");
        amonth.add("February");
        amonth.add("March");
        amonth.add("April");
        amonth.add("May");
        amonth.add("June");
        amonth.add("July");
        amonth.add("August");
        amonth.add("September");
        amonth.add("October");
        amonth.add("November");
        amonth.add("December");
        
        mmonth.add("Full Year");
        mmonth.add("January");
        mmonth.add("February");
        mmonth.add("March");
        mmonth.add("April");
        mmonth.add("May");
        mmonth.add("June");
        mmonth.add("July");
        mmonth.add("August");
        mmonth.add("September");
        mmonth.add("October");
        mmonth.add("November");
        mmonth.add("December");
        
        lmonth.add("Full Year");
        lmonth.add("January");
        lmonth.add("February");
        lmonth.add("March");
        lmonth.add("April");
        lmonth.add("May");
        lmonth.add("June");
        lmonth.add("July");
        lmonth.add("August");
        lmonth.add("September");
        lmonth.add("October");
        lmonth.add("November");
        lmonth.add("December");
        
        umonth2.add("Full Year");
        umonth2.add("January");
        umonth2.add("February");
        umonth2.add("March");
        umonth2.add("April");
        umonth2.add("May");
        umonth2.add("June");
        umonth2.add("July");
        umonth2.add("August");
        umonth2.add("September");
        umonth2.add("October");
        umonth2.add("November");
        umonth2.add("December");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        umonth = new java.awt.Choice();
        jLabel11 = new javax.swing.JLabel();
        uyear = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        unit = new javax.swing.JLabel();
        checkunitdetails = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tmonth = new java.awt.Choice();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbillyear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalbill = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checktotalbill = new javax.swing.JButton();
        bmonth = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();
        byear = new javax.swing.JTextField();
        checkbillstatus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        meterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        amonth = new java.awt.Choice();
        jLabel18 = new javax.swing.JLabel();
        tyear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        averagebill = new javax.swing.JLabel();
        ubcheck = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        lbill = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lmonth = new java.awt.Choice();
        jLabel21 = new javax.swing.JLabel();
        ayear = new javax.swing.JTextField();
        checkaveragebill1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        mbill1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        mmonth = new java.awt.Choice();
        jLabel24 = new javax.swing.JLabel();
        mbillyear = new javax.swing.JTextField();
        mcheck1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        u1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        u2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        umonth2 = new java.awt.Choice();
        jLabel28 = new javax.swing.JLabel();
        uyear2 = new javax.swing.JTextField();
        lcheck1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(umonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 111, 35));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Enter Year:*");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        uyear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(uyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 96, 33));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Unit Consumed:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, 33));

        unit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unit.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 112, 34));

        checkunitdetails.setBackground(new java.awt.Color(204, 255, 255));
        checkunitdetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkunitdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        checkunitdetails.setText("Check");
        checkunitdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkunitdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(checkunitdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, 35));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Select Month:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 35));
        getContentPane().add(tmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 111, 35));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Enter Year:*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Oxygen-Icons.org-Oxygen-Actions-view-list-details.24.png"))); // NOI18N
        jLabel1.setText(" Bill Details ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 220, -1));

        lbillyear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbillyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 96, 33));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Meter No:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 28));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("View Total Bill:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Total Bill:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bill Status:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        totalbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalbill.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(totalbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 154, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Select Month:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 34));

        checktotalbill.setBackground(new java.awt.Color(204, 255, 255));
        checktotalbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checktotalbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        checktotalbill.setText("Check");
        checktotalbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checktotalbillActionPerformed(evt);
            }
        });
        getContentPane().add(checktotalbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, 35));
        getContentPane().add(bmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 111, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Enter Year:*");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        byear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(byear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 96, 33));

        checkbillstatus.setBackground(new java.awt.Color(204, 255, 255));
        checkbillstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbillstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        checkbillstatus.setText("Check");
        checkbillstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbillstatusActionPerformed(evt);
            }
        });
        getContentPane().add(checkbillstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Status:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 51, 33));

        status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 130, 100, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Units Details:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Select Month:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 35));

        meterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(meterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 141, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("View Average Bill:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Select Month:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 25));
        getContentPane().add(amonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 111, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Enter Year:*");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, 30));

        tyear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(tyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 99, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Average Bill:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 90, 30));

        averagebill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        averagebill.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(averagebill, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 126, 34));

        ubcheck.setBackground(new java.awt.Color(204, 255, 255));
        ubcheck.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubcheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        ubcheck.setText("Check");
        ubcheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ubcheckMouseEntered(evt);
            }
        });
        ubcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubcheckActionPerformed(evt);
            }
        });
        getContentPane().add(ubcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, -1, 35));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("And:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, 36));

        lbill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 130, 36));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Select Month:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 100, 40));
        getContentPane().add(lmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 120, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Enter Year:*");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, 30));

        ayear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ayear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ayearMouseEntered(evt);
            }
        });
        getContentPane().add(ayear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 96, 33));

        checkaveragebill1.setBackground(new java.awt.Color(204, 255, 255));
        checkaveragebill1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkaveragebill1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        checkaveragebill1.setText("Check");
        checkaveragebill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkaveragebill1ActionPerformed(evt);
            }
        });
        getContentPane().add(checkaveragebill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, 35));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("View Bill More Than or Equal:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 200, 40));

        mbill1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mbill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbill1ActionPerformed(evt);
            }
        });
        getContentPane().add(mbill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 130, 36));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Select Month:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, 25));
        getContentPane().add(mmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 120, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Enter Year:*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, 30));

        mbillyear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(mbillyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 96, 33));

        mcheck1.setBackground(new java.awt.Color(204, 255, 255));
        mcheck1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mcheck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        mcheck1.setText("Check");
        mcheck1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mcheck1MouseEntered(evt);
            }
        });
        mcheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcheck1ActionPerformed(evt);
            }
        });
        getContentPane().add(mcheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, -1, 35));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("View Bill Less Than or Equal:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 36));

        u1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 120, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("View Unit Between:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, 36));

        u2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(u2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 110, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Select Month:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 100, 40));
        getContentPane().add(umonth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 110, 40));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Enter Year:*");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, 30));

        uyear2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(uyear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 90, 40));

        lcheck1.setBackground(new java.awt.Color(204, 255, 255));
        lcheck1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lcheck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        lcheck1.setText("Check");
        lcheck1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lcheck1MouseEntered(evt);
            }
        });
        lcheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcheck1ActionPerformed(evt);
            }
        });
        getContentPane().add(lcheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, -1, 35));

        table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Meter No", "Bill Entry Date", "Billing Month", "Billing Year", "Units", "Total Bill", "Status"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1000, 180));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Oxygen-Icons.org-Oxygen-Actions-edit-delete.24.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 110, 40));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel30.setText(" -");
        jLabel30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 30));

        print.setBackground(new java.awt.Color(204, 255, 204));
        print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Treetog-Junior-Printer.24.png"))); // NOI18N
        print.setText("Print ");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 110, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mbill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbill1ActionPerformed

    private void checkbillstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbillstatusActionPerformed
        
        
        String smeter = meterno.getText();
        String smonth = bmonth.getSelectedItem();
        String syear = byear.getText();
        
        
         try {
            Conn c = new Conn();
              
           if(smeter.equals("") || syear.equals("")){
               if(smeter.equals("")){
                   JOptionPane.showMessageDialog(null, "Please Enter a Meter No!!");
               }else{
                   JOptionPane.showMessageDialog(null, "Please Enter a year!!");
               }
               
                
               
           }else{
               
             ResultSet rs = c.s.executeQuery("select * from bill where meter_no = '"+smeter+"' and billing_month = '"+smonth+"' and  billing_year = '"+syear+"'");
           if(rs.next()) {
       
                status.setText(rs.getString("status"));
            }else {
                JOptionPane.showMessageDialog(null, "Meter Number Not Found!! OR This Meter Doesn't Exist in "+syear+" and "+smonth+"");
                meterno.setText("");
            }
           } 
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_checkbillstatusActionPerformed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkunitdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkunitdetailsActionPerformed
        String smeter = meterno.getText();
        String smonth = umonth.getSelectedItem();
        String syear = uyear.getText();
        
        
         try {
            Conn c = new Conn();
            
            if(smeter.equals("") || syear.equals("")){
               if(smeter.equals("")){
                   JOptionPane.showMessageDialog(null, "Please Enter a Meter No!!");
               }else{
                   JOptionPane.showMessageDialog(null, "Please Enter a year!!");
               }
               
                
               
           }else{
                 ResultSet rs = c.s.executeQuery("select * from bill where meter_no = '"+smeter+"' and billing_month = '"+smonth+"' and  billing_year = '"+syear+"'");  
            
            if(rs.next()) {
       
                unit.setText(rs.getString("units"));
            }else {
                JOptionPane.showMessageDialog(null, "Meter Number Not Found!! OR This Meter Doesn't Exist in "+syear+"");
                meterno.setText("");
            }
            }  
        } catch (Exception e) {
            e.printStackTrace();
        }
            
            
           
    }//GEN-LAST:event_checkunitdetailsActionPerformed

    private void checktotalbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checktotalbillActionPerformed
        String smeter = meterno.getText();
        String smonth = tmonth.getSelectedItem();
        String syear = tyear.getText();
        
        
         try {
            Conn c = new Conn();
            
            
            if(smeter.equals("") || syear.equals("")){
               if(smeter.equals("")){
                   JOptionPane.showMessageDialog(null, "Please Enter a Meter No!!");
               }else{
                   JOptionPane.showMessageDialog(null, "Please Enter a year!!");
               }
               
                
               
           }else{
                ResultSet rs = c.s.executeQuery("select * from bill where meter_no = '"+smeter+"' and billing_month = '"+smonth+"' and  billing_year = '"+syear+"'");  
            
            if(rs.next()) {
       
                totalbill.setText(rs.getString("totalbill"));
            }else {
                JOptionPane.showMessageDialog(null, "Meter Number Not Found!! OR This Meter Doesn't Exist in "+syear+"");
                meterno.setText("");
            }
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_checktotalbillActionPerformed

    private void checkaveragebill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkaveragebill1ActionPerformed
        String smeter = meterno.getText();
        String smonth = amonth.getSelectedItem();
        String syear = ayear.getText();
        
        
         try {
            Conn c = new Conn();
            
            
                if(smeter.equals("")){
                if(smonth.equals("Full Year")){
                    String query = "select AVG(totalbill) as AvgTotalBill from bill where billing_year = '"+syear+"'";
                    ResultSet rs = c.s.executeQuery(query);
                    while(rs.next()){
                        averagebill.setText(rs.getString("AvgTotalBill"));
                    }
      
                }else{
                    String query1 = "select AVG(totalbill) as AvgTotalBill from bill where billing_month = '"+smonth+"' and  billing_year = '"+syear+"'";
                    ResultSet rs = c.s.executeQuery(query1);
                    while(rs.next()){
                    averagebill.setText(rs.getString("AvgTotalBill"));
                    }
                }
            }
                          else {
                    
                    if (syear.equals("")){
                    JOptionPane.showMessageDialog(null, "Please Enter a Year");
                }else{
                String query2 = "select AVG(totalbill) as AvgTotalBill from bill where meter_no = '"+smeter+"' and billing_year = '"+syear+"'";
                    ResultSet rs = c.s.executeQuery(query2);
                    while(rs.next()){
                        averagebill.setText(rs.getString("AvgTotalBill"));
                    }
                    }
            }
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_checkaveragebill1ActionPerformed

    private void ubcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubcheckActionPerformed
       String smeter = meterno.getText();
        String smonth = umonth2.getSelectedItem();
        String syear = uyear2.getText();
        String unit1 = u1.getText();
        String unit2 = u2.getText();
        
        
        
         try {
            Conn c = new Conn();
            if(smeter.equals("")){
                if(smonth.equals("Full Year")){
                    if(unit1.equals("") && unit2.equals("")){
                        JOptionPane.showMessageDialog(null, "Unit values Cannot be Empty Or Enter Correct Unit Valus!!");
                    }else{
                        String query = "select * from bill where billing_year = '"+syear+"' and units between '"+unit1+".00000' and '"+unit2+".00000'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                    table.setModel(DbUtils.resultSetToTableModel(rs));
                    
                    }
      
                }else{
                    String query = "select * from bill where billing_month = '"+smonth+"' and  billing_year = '"+syear+"' and units between '"+unit1+".00000' and '"+unit2+".00000'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                    table.setModel(DbUtils.resultSetToTableModel(rs));
                }
            }else {
                String query = "select * from bill where meter_no = '"+smeter+"' and  billing_year = '"+syear+"' and units between '"+unit1+".00000' and '"+unit2+".00000'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                    table.setModel(DbUtils.resultSetToTableModel(rs));
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ubcheckActionPerformed

    private void mcheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcheck1ActionPerformed
         String smeter = meterno.getText();
        String smonth = mmonth.getSelectedItem();
        String syear = mbillyear.getText();
        String morebill = mbill1.getText();
        
        
        
        
         try {
            Conn c = new Conn();
             
            if(smeter.equals("")){
                if(smonth.equals("Full Year")){
                    
                        String query = "select * from bill where billing_year = '"+syear+"' and totalbill >= '"+morebill+"'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                    table.setModel(DbUtils.resultSetToTableModel(rs));
                    
                    
      
                }else{
                    String query = "select * from bill where billing_year = '"+syear+"' and billing_month = '"+smonth+"' and totalbill >= '"+morebill+"'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                    table.setModel(DbUtils.resultSetToTableModel(rs));
                }
            }else {
                
                String query = "select * from bill where meter_no = '"+smeter+"' and  billing_year = '"+syear+"' and totalbill >= '"+morebill+"'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                   
                       table.setModel(DbUtils.resultSetToTableModel(rs));
                       
                   
                     
                        
            
                   }
                    
                
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mcheck1ActionPerformed

    private void lcheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcheck1ActionPerformed
        String smeter = meterno.getText();
        String smonth = lmonth.getSelectedItem();
        String syear = lbillyear.getText();
        String lessbill = lbill.getText();
        
        
        
        
          try {
            Conn c = new Conn();
             
            if(smeter.equals("")){
                if(smonth.equals("Full Year")){
                    
                        String query = "select * from bill where billing_year = '"+syear+"' and totalbill <= '"+lessbill+"'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                    table.setModel(DbUtils.resultSetToTableModel(rs));
                    
                    
      
                }else{
                    String query = "select * from bill where billing_year = '"+syear+"' and billing_month = '"+smonth+"' and totalbill <= '"+lessbill+"'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                    table.setModel(DbUtils.resultSetToTableModel(rs));
                }
            }else {
                
                String query = "select * from bill where meter_no = '"+smeter+"' and  billing_year = '"+syear+"' and totalbill <= '"+lessbill+"'";
                    ResultSet rs = c.s.executeQuery(query);
                    
                   
                       table.setModel(DbUtils.resultSetToTableModel(rs));
                       
                   
                     
                        
            
                   }
                    
                
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lcheck1ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            table.print();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_printActionPerformed

    private void ayearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayearMouseEntered
        
    }//GEN-LAST:event_ayearMouseEntered

    private void mcheck1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcheck1MouseEntered
        String bill = mbill1.getText();
        String syear = mbillyear.getText();
        
        if (bill.equals("") || syear.equals("")){
            mcheck1.setEnabled(false);
        }else{
            mcheck1.setEnabled(true);
        }
    }//GEN-LAST:event_mcheck1MouseEntered

    private void lcheck1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcheck1MouseEntered
        String bill = lbill.getText();
        String syear = lbillyear.getText();
        
        if (bill.equals("") || syear.equals("")){
            lcheck1.setEnabled(false);
        }else{
            lcheck1.setEnabled(true);
        }
    }//GEN-LAST:event_lcheck1MouseEntered

    private void ubcheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubcheckMouseEntered
        String su1 = u1.getText();
        String su2 = u2.getText();
        String syear = uyear2.getText();
        if (su1.equals("") || syear.equals("") || su2.equals("")){
            ubcheck.setEnabled(false);
        }else{
            ubcheck.setEnabled(true);
        }
    }//GEN-LAST:event_ubcheckMouseEntered

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        positionX = evt.getX();
        positionY = evt.getY();


    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDetailsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice amonth;
    private javax.swing.JLabel averagebill;
    private javax.swing.JTextField ayear;
    private java.awt.Choice bmonth;
    private javax.swing.JTextField byear;
    private javax.swing.JButton checkaveragebill1;
    private javax.swing.JButton checkbillstatus;
    private javax.swing.JButton checktotalbill;
    private javax.swing.JButton checkunitdetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbill;
    private javax.swing.JTextField lbillyear;
    private javax.swing.JButton lcheck1;
    private java.awt.Choice lmonth;
    private javax.swing.JTextField mbill1;
    private javax.swing.JTextField mbillyear;
    private javax.swing.JButton mcheck1;
    private javax.swing.JTextField meterno;
    private java.awt.Choice mmonth;
    private javax.swing.JButton print;
    private javax.swing.JLabel status;
    private javax.swing.JTable table;
    private java.awt.Choice tmonth;
    private javax.swing.JLabel totalbill;
    private javax.swing.JTextField tyear;
    private javax.swing.JTextField u1;
    private javax.swing.JTextField u2;
    private javax.swing.JButton ubcheck;
    private java.awt.Choice umonth;
    private java.awt.Choice umonth2;
    private javax.swing.JLabel unit;
    private javax.swing.JTextField uyear;
    private javax.swing.JTextField uyear2;
    // End of variables declaration//GEN-END:variables
}
