/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Zim
 */
public class BillDetailsUser extends javax.swing.JFrame {

   
int positionX = 0, positionY=0;


    public BillDetailsUser() {
        initComponents();
        
         
        
    }
    
    public BillDetailsUser(String smeter) {
        initComponents();
        
        meterno.setText(smeter);
        
        bmonth.add("January");
        bmonth.add("February");
        bmonth.add("March");
        bmonth.add("April");
        bmonth.add("May");
        bmonth.add("June");
        bmonth.add("July");
        bmonth.add("August");
        bmonth.add("September");
        bmonth.add("October");
        bmonth.add("November");
        bmonth.add("December");
        
        umonth.add("January");
        umonth.add("February");
        umonth.add("March");
        umonth.add("April");
        umonth.add("May");
        umonth.add("June");
        umonth.add("July");
        umonth.add("August");
        umonth.add("September");
        umonth.add("October");
        umonth.add("November");
        umonth.add("December");
        
        tmonth.add("January");
        tmonth.add("February");
        tmonth.add("March");
        tmonth.add("April");
        tmonth.add("May");
        tmonth.add("June");
        tmonth.add("July");
        tmonth.add("August");
        tmonth.add("September");
        tmonth.add("October");
        tmonth.add("November");
        tmonth.add("December");
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        meterno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bmonth = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();
        byear = new javax.swing.JTextField();
        checkbillstatus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        umonth = new java.awt.Choice();
        jLabel11 = new javax.swing.JLabel();
        uyear = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        unit = new javax.swing.JLabel();
        checkunitdetails = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tmonth = new java.awt.Choice();
        jLabel14 = new javax.swing.JLabel();
        tyear = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        totalbill = new javax.swing.JLabel();
        checktotalbill = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Oxygen-Icons.org-Oxygen-Actions-view-list-details.24.png"))); // NOI18N
        jLabel1.setText(" Bill Details ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 38, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Meter No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 113, -1, -1));

        meterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(meterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 113, 145, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Check Your Bill Status: ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 159, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Select Month:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 198, -1, 34));
        jPanel1.add(bmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 198, 111, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Enter Year:*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 206, -1, -1));

        byear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(byear, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 199, 77, 33));

        checkbillstatus.setBackground(new java.awt.Color(204, 255, 255));
        checkbillstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbillstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        checkbillstatus.setText("Check");
        checkbillstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkbillstatusMouseEntered(evt);
            }
        });
        checkbillstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbillstatusActionPerformed(evt);
            }
        });
        jPanel1.add(checkbillstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 197, -1, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Status:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 198, 51, 33));

        status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 197, 85, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Units Details:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 242, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Select Month:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 273, -1, 34));
        jPanel1.add(umonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 273, 111, 34));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Enter Year:*");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 281, -1, -1));

        uyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(uyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 274, 77, 33));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Unit Consumed:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 273, -1, 33));

        unit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unit.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 273, 85, 34));

        checkunitdetails.setBackground(new java.awt.Color(204, 255, 255));
        checkunitdetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkunitdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        checkunitdetails.setText("Check");
        checkunitdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkunitdetailsMouseEntered(evt);
            }
        });
        checkunitdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkunitdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(checkunitdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 272, -1, 35));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Select Month:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 344, -1, 35));
        jPanel1.add(tmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 344, 111, 35));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Enter Year:*");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 353, -1, -1));

        tyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(tyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 346, 74, 33));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("View Total Bill:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 317, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Total Bill:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 345, -1, 33));

        totalbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalbill.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(totalbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 344, 160, 34));

        checktotalbill.setBackground(new java.awt.Color(204, 255, 255));
        checktotalbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checktotalbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        checktotalbill.setText("Check");
        checktotalbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checktotalbillMouseEntered(evt);
            }
        });
        checktotalbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checktotalbillActionPerformed(evt);
            }
        });
        jPanel1.add(checktotalbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 344, -1, 35));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText(" -");
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 26, 32));

        back.setBackground(new java.awt.Color(204, 255, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Oxygen-Icons.org-Oxygen-Actions-edit-delete.24.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, 36));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Thinking Emoji GIF For Whats App Free.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 320, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void checkbillstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbillstatusActionPerformed
        
        String smeter = meterno.getText();
        String smonth = bmonth.getSelectedItem();
        String syear = byear.getText();
        
        
         try {
            Conn c = new Conn();
            ResultSet rs = c.s.executeQuery("select * from bill where meter_no = '"+smeter+"' and billing_month = '"+smonth+"' and  billing_year = '"+syear+"'");  
            
            if(rs.next()) {
       
                status.setText(rs.getString("status"));
            }else{
                JOptionPane.showMessageDialog(null, "This Meter No Doesn't Exist in "+smonth+" of "+syear+"");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_checkbillstatusActionPerformed

    private void checkunitdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkunitdetailsActionPerformed
        String smeter = meterno.getText();
        String smonth = umonth.getSelectedItem();
        String syear = uyear.getText();
        
        
         try {
            Conn c = new Conn();
            ResultSet rs = c.s.executeQuery("select * from bill where meter_no = '"+smeter+"' and billing_month = '"+smonth+"' and  billing_year = '"+syear+"'");  
            
            if(rs.next()) {
       
                unit.setText(rs.getString("units"));
            }else{
                 JOptionPane.showMessageDialog(null, "This Meter No Doesn't Exist in "+smonth+" of "+syear+"");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_checkunitdetailsActionPerformed

    private void checktotalbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checktotalbillActionPerformed
        String smeter = meterno.getText();
        String smonth = tmonth.getSelectedItem();
        String syear = tyear.getText();
        
        
         try {
            Conn c = new Conn();
            ResultSet rs = c.s.executeQuery("select * from bill where meter_no = '"+smeter+"' and billing_month = '"+smonth+"' and  billing_year = '"+syear+"'");  
            
            if(rs.next()) {
       
                totalbill.setText(rs.getString("totalbill"));
            }else{
                 JOptionPane.showMessageDialog(null, "This Meter No Doesn't Exist in "+smonth+" of "+syear+"");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_checktotalbillActionPerformed

    private void checkbillstatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkbillstatusMouseEntered
        
        String syear = byear.getText();
        
        if (syear.equals("")){
            checkbillstatus.setEnabled(false);
        }else{
            checkbillstatus.setEnabled(true);
        }
    }//GEN-LAST:event_checkbillstatusMouseEntered

    private void checkunitdetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkunitdetailsMouseEntered
        String syear = uyear.getText();
        
        if (syear.equals("")){
            checkunitdetails.setEnabled(false);
        }else{
            checkunitdetails.setEnabled(true);
        }
    }//GEN-LAST:event_checkunitdetailsMouseEntered

    private void checktotalbillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checktotalbillMouseEntered
       String syear = tyear.getText();
        
        if (syear.equals("")){
            checktotalbill.setEnabled(false);
        }else{
            checktotalbill.setEnabled(true);
        }
    }//GEN-LAST:event_checktotalbillMouseEntered

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        positionX = evt.getX();
        positionY = evt.getY();


    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetailsUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetailsUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetailsUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetailsUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDetailsUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private java.awt.Choice bmonth;
    private javax.swing.JTextField byear;
    private javax.swing.JButton checkbillstatus;
    private javax.swing.JButton checktotalbill;
    private javax.swing.JButton checkunitdetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel meterno;
    private javax.swing.JLabel status;
    private java.awt.Choice tmonth;
    private javax.swing.JLabel totalbill;
    private javax.swing.JTextField tyear;
    private java.awt.Choice umonth;
    private javax.swing.JLabel unit;
    private javax.swing.JTextField uyear;
    // End of variables declaration//GEN-END:variables
}
