/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;


import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Date;

import javax.swing.*;

/**
 *
 * @author Zim
 */
public class Customer extends javax.swing.JFrame {

    
int positionX = 0, positionY=0;


     
    public Customer() {
        initComponents();
        
        
        Random ran = new Random();
        long number = ran.nextLong() % 1000000;
        meter.setText("" + Math.abs(number));
        date.setDate(new Date());
        ques.add("What is your pet name ?");
        ques.add("What is your father name ?");
        ques.add("What is your favourite sports ?");
        ques.add("What is your favourite book name ?");
        ques.add("Where were you born ?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        meter = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        caddress = new javax.swing.JTextField();
        ccity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cnid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cpass = new javax.swing.JPasswordField();
        cphone = new javax.swing.JTextField();
        cphone2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ques = new java.awt.Choice();
        jLabel9 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Everaldo-Crystal-Clear-App-login-manager.32.png"))); // NOI18N
        jLabel1.setText("Customer Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 35));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        cname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        jPanel1.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 205, 32));

        meter.setBackground(new java.awt.Color(255, 255, 255));
        meter.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        meter.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(meter, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 200, 28));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 67, 29));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("City:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        caddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        caddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 205, 32));

        ccity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ccity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(ccity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 205, 32));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Meter No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        cemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cemail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 205, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Answer:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 307, -1, 20));

        cnid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cnid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cnid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnidKeyPressed(evt);
            }
        });
        jPanel1.add(cnid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 205, 32));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        create.setBackground(new java.awt.Color(204, 255, 255));
        create.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tatice-Cristal-Intense-Ok.24.png"))); // NOI18N
        create.setText("Create");
        create.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 110, 40));

        back.setBackground(new java.awt.Color(204, 255, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Graphicloads-100-Flat-2-Arrow-back.24.png"))); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 100, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("NID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Fatcow-Farm-Fresh-Caution-high-voltage.24.png"))); // NOI18N
        jLabel11.setText(" Please note your Meter No for Future Login!!");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 0)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 330, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date Of Birth:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 100, 30));

        cpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 205, 32));

        cphone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cphone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 205, 32));

        cphone2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cphone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 205, 32));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText(" X");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 10, 30, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" -");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 40, 30));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Light-Eye-off.32.png"))); // NOI18N
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel1.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 30, 30));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Custom-Icon-Design-Pretty-Office-8-Eye.32.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 30, 30));

        jLabel15.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone : *");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        ques.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 220, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Security Question:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        ans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 210, 30));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 200, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/signupc.jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        new userlogin().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        String csname = cname.getText();
            String smeter = meter.getText();
            String csaddress = caddress.getText();
            String cscity = ccity.getText();
            String cspass = cpass.getText();
            String csemail = cemail.getText();
            String csphone = cphone.getText();
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String sdate = df.format(date.getDate());
            String csnid = cnid.getText();
            String sques = ques.getSelectedItem();
            String sans = ans.getText();
            
            
            
            
            
            try{
                
                Conn c = new Conn();  
                
                if (csname.equals("") || smeter.equals("") || csaddress.equals("") || 
                        cscity.equals("") || cspass.equals("") || csemail.equals("") || 
                        csphone.equals("") || sdate.equals("") || csnid.equals("") || sques.equals("") || sans.equals("")) {
                
                JOptionPane.showMessageDialog(null, "All Fields are Required!!");
            }else if (!isValidEmail(csemail)){
                JOptionPane.showMessageDialog(null, "Please enter a valid email address!!");
            }else if (!isInteger(csphone)){
                JOptionPane.showMessageDialog(null, "Please Enter the phone number in integer format!!");
               
            }else if (!isInteger(csnid)){
                JOptionPane.showMessageDialog(null, "Please Enter the NID in integer format!!");
            }
            else {
                
               
                String query = "insert into customer values('"+csname+"', '"+smeter+"', '"+csaddress+"', '"+cscity+"', '"+csemail+"', '"+csphone+"', '"+cspass+"', '"+sdate+"', '"+csnid+"', '"+sques+"', '"+sans+"')";
                c.s.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Customer Account Successfully Created");
                
                
                setVisible(false);
                new meter_info(smeter).setVisible(true);
            }
                
                
               
            }catch (Exception e){
                e.printStackTrace();
            }
            
    }//GEN-LAST:event_createActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Do You want to Exit the Application?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
          System.exit(0);  
        }else{
            
        }
        
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
         cpass.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
        
        
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
         cpass.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void cnidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String csname = cname.getText();
            String smeter = meter.getText();
            String csaddress = caddress.getText();
            String cscity = ccity.getText();
            String cspass = cpass.getText();
            String csemail = cemail.getText();
            String csphone = cphone.getText();
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String sdate = df.format(date.getDate());
            String csnid = cnid.getText();
            String sques = ques.getSelectedItem();
            String sans = ans.getText();
            
            
            
            
            
            try{
                
                Conn c = new Conn();  
                
                if (csname.equals("") || smeter.equals("") || csaddress.equals("") || 
                        cscity.equals("") || cspass.equals("") || csemail.equals("") || 
                        csphone.equals("") || sdate.equals("") || csnid.equals("") || sques.equals("") || sans.equals("")) {
                
                JOptionPane.showMessageDialog(null, "All Fields are Required!!");
            }else if (!isValidEmail(csemail)){
                JOptionPane.showMessageDialog(null, "Please enter a valid email address!!");
            }else if (!isInteger(csphone)){
                JOptionPane.showMessageDialog(null, "Please Enter the phone number in integer format!!");
               
            }else if (!isInteger(csnid)){
                JOptionPane.showMessageDialog(null, "Please Enter the NID in integer format!!");
            }
            else {
                
               
                String query = "insert into customer values('"+csname+"', '"+smeter+"', '"+csaddress+"', '"+cscity+"', '"+csemail+"', '"+csphone+"', '"+cspass+"', '"+sdate+"', '"+csnid+"', '"+sques+"', '"+sans+"')";
                c.s.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Customer Account Successfully Created");
                
                
                setVisible(false);
                new meter_info(smeter).setVisible(true);
            }
                
                
               
            }catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cnidKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       positionX = evt.getX();
        positionY = evt.getY();


    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_formMouseDragged

    public static boolean isInteger(String str) {
        
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
   
    
    public static boolean isValidEmail(String email) {
    String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    return email != null && email.matches(emailRegex);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JButton back;
    private javax.swing.JTextField caddress;
    private javax.swing.JTextField ccity;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnid;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JTextField cphone;
    private javax.swing.JTextField cphone2;
    private javax.swing.JButton create;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel meter;
    private java.awt.Choice ques;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
