/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;


import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Zim
 */
public class ForgotPassUser extends javax.swing.JFrame {

    
int positionX = 0, positionY=0;


    public ForgotPassUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        meterno = new javax.swing.JTextField();
        ans = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        change = new javax.swing.JButton();
        back = new javax.swing.JButton();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        ques = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("USER PASSWORD RECOVERY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 46));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Meter\\Phone No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Security Question:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Answer:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("New Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 121, 33));

        meterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(meterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 205, 36));

        ans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 210, 39));

        pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 210, 33));

        change.setBackground(new java.awt.Color(204, 255, 255));
        change.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Simiographics-Secure-Key.32.png"))); // NOI18N
        change.setText("Change");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 130, 30));

        back.setBackground(new java.awt.Color(255, 204, 204));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Graphicloads-100-Flat-2-Arrow-back.24.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Light-Eye-off.32.png"))); // NOI18N
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel1.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 33));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Custom-Icon-Design-Pretty-Office-8-Eye.32.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 33));

        checkbox.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        checkbox.setForeground(new java.awt.Color(255, 255, 255));
        checkbox.setText("For Security Question Please Check the Box");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 270, -1));

        ques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ques.setText("jLabel6");
        jPanel1.add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        String smeter = meterno.getText();

        String sans = ans.getText();
        String sques = ques.getText();

        String spass = pass.getText();

        try{

            Conn c = new Conn();

            String query = "select * from customer where meter_no= '"+smeter+"'";
            ResultSet rs = c.s.executeQuery(query);
            if (rs.next()){
                    
                String query1 = "select * from customer where meter_no= '"+smeter+"' or phone = '"+smeter+"' and Security_Question = '"+sques+"' and answer = '"+sans+"'";
            ResultSet ra = c.s.executeQuery(query1);
             if(ra.next()){
                 String query2 = "update customer set PASSWORD = '"+spass+"' where Security_Question = '"+sques+"' and meter_no = '"+smeter+"'";

                c.s.executeUpdate(query2);
                JOptionPane.showMessageDialog(null, "Successfully Changed Your Password!!");
                setVisible(false);
                new userlogin().setVisible(true);
             }else if(!isInteger(smeter)){
            
                 JOptionPane.showMessageDialog(null, "Please Enter the Meter or Phone Number in Integer Format!!!");
            }else{
                 JOptionPane.showMessageDialog(null, "Wrong Security Question or Answer!!");
                  ques.setText("");
                  ans.setText("");
             }
                       
            }else{
                JOptionPane.showMessageDialog(null, "Please create an account first!!");
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_changeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        new userlogin().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        pass.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        pass.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        String smeter = meterno.getText();

        try{

            Conn c = new Conn();

            String query = "select * from customer where meter_no= '"+smeter+"' or phone = '"+smeter+"'";
            ResultSet rs = c.s.executeQuery(query);
            if (rs.next()){
                ques.setText(rs.getString("Security_Question"));
            }else if(!isInteger(smeter)){
            
                 JOptionPane.showMessageDialog(null, "Please Enter the Meter or Phone Number in Integer Format!!!");
            }else{
                JOptionPane.showMessageDialog(null, "This Meter  Doesn't Exists");
                checkbox.setSelected(false);
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String smeter = meterno.getText();

        String sans = ans.getText();
        String sques = ques.getText();

        String spass = pass.getText();

        try{

            Conn c = new Conn();

            String query = "select * from customer where meter_no= '"+smeter+"'";
            ResultSet rs = c.s.executeQuery(query);
            if (rs.next()){
                    
                String query1 = "select * from customer where meter_no= '"+smeter+"' or phone = '"+smeter+"' and Security_Question = '"+sques+"' and answer = '"+sans+"'";
            ResultSet ra = c.s.executeQuery(query1);
             if(ra.next()){
                 String query2 = "update customer set PASSWORD = '"+spass+"' where Security_Question = '"+sques+"' and meter_no = '"+smeter+"'";

                c.s.executeUpdate(query2);
                JOptionPane.showMessageDialog(null, "Successfully Changed Your Password!!");
                setVisible(false);
                new userlogin().setVisible(true);
             }else if(!isInteger(smeter)){
            
                 JOptionPane.showMessageDialog(null, "Please Enter the Meter or Phone Number in Integer Format!!!");
            }else{
                 JOptionPane.showMessageDialog(null, "Wrong Security Question or Answer!!");
                  ques.setText("");
                  ans.setText("");
             }
                       
            }else{
                JOptionPane.showMessageDialog(null, "Please create an account first!!");
            }

        }catch(Exception e){
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_passKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        positionX = evt.getX();
        positionY = evt.getY();


    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_formMouseDragged

    
    
     public static boolean isInteger(String str) {
        
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JButton back;
    private javax.swing.JButton change;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField meterno;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel ques;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
