/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;

import java.util.Date;

/**
 *
 * @author Zim
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    String smonth;
    String syear;
    public Payment() {
        initComponents();
        date.setDate(new Date());
    }
    
    public Payment(String smeter, String sname, String amount, String smonth, String syear) {
        initComponents();
        this.smonth = smonth;
        this.syear = syear;
        a.setText(amount);
        meterno.setText(smeter);
        name.setText(sname);
        date.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        meterno = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        bn = new javax.swing.JTextField();
        pin = new javax.swing.JPasswordField();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        back = new javax.swing.JButton();
        generatebill = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Screenshot 2024-05-09 173502.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 400, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bkash.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 1280, 270));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 20, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Amount:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 50, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Bkash No:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 40, 30));

        meterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(meterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 220, 30));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 220, 30));

        bn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(bn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 220, 40));

        pin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        jPanel1.add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 220, 40));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Light-Eye-off.32.png"))); // NOI18N
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel1.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 30, 40));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Custom-Icon-Design-Pretty-Office-8-Eye.32.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, 40));

        pay.setBackground(new java.awt.Color(133, 232, 231));
        pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Simpleicons-Team-Simple-Amazon-pay.24.png"))); // NOI18N
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payMouseEntered(evt);
            }
        });
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        jPanel1.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 80, -1));

        back.setBackground(new java.awt.Color(255, 153, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Oxygen-Icons.org-Oxygen-Actions-edit-delete.24.png"))); // NOI18N
        back.setText("Cancel");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, 30));

        generatebill.setBackground(new java.awt.Color(153, 255, 153));
        generatebill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generatebill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Treetog-Junior-Printer.24.png"))); // NOI18N
        generatebill.setText("Bill Receipt");
        generatebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebillActionPerformed(evt);
            }
        });
        jPanel1.add(generatebill, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Fatcow-Farm-Fresh-Caution-high-voltage.24.png"))); // NOI18N
        jLabel8.setText("Once payment is done, the money will not refundable !!");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 330, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Fatcow-Farm-Fresh-Caution-high-voltage.24.png"))); // NOI18N
        jLabel9.setText("So, please check your amount, meter number and name before payment.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Meter No:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 70, 30));

        a.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Bkash PIN:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i=i+0.1 ){
          String win = i + "";
          float o = Float.parseFloat(win);
          this.setOpacity(o);
          try{
              Thread.sleep(50);
          }catch (Exception e){
              e.printStackTrace();
          }
          
      }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       int response = JOptionPane.showConfirmDialog(this, "Do You want to Exit the Application?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
          System.exit(0);  
        }else{
            
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        pin.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        
        pin.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        
    }//GEN-LAST:event_pinActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        
    }//GEN-LAST:event_backActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        String smeter = meterno.getText();
        String sphone = bn.getText();
        String samount = a.getText();
        String amonth = smonth;
        String ayear = syear;
        String spin = pin.getText();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String sdate = df.format(date.getDate());
                if((sphone.equals("") || spin.equals("") || sdate.equals(""))){
                    
                }else{
        try{
            
            Conn c = new Conn();
            
            String query = "insert into transaction values('"+smeter+"', '"+sphone+"', '"+samount+"', '"+sdate+"')";
                c.s.executeUpdate(query);
                String query1 = "update bill set status = 'Paid' where meter_no = '"+smeter+"' and billing_month = '"+amonth+"' and billing_year = '"+ayear+"'";
                c.s.executeUpdate(query1);
                 JOptionPane.showMessageDialog(null, "Payment Successfull");
            
        }catch(Exception e){
            e.printStackTrace();
        }
                }
        
    }//GEN-LAST:event_payActionPerformed

    private void generatebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebillActionPerformed
        String smeter = meterno.getText();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String sdate = df.format(date.getDate());
        
        setVisible(false);
        new GenerateBill(smeter, smonth, syear, sdate).setVisible(true);
    }//GEN-LAST:event_generatebillActionPerformed

    private void payMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseEntered
         String sphone = bn.getText();
        String spin = pin.getText();
        
            Date sdate = date.getDate();
        
        if (sphone.equals("") || spin.equals("") || sdate == null){
            pay.setEnabled(false);
        }else{
            pay.setEnabled(true);
        }
        
    }//GEN-LAST:event_payMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton back;
    private javax.swing.JTextField bn;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel disable;
    private javax.swing.JButton generatebill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel meterno;
    private javax.swing.JLabel name;
    private javax.swing.JButton pay;
    private javax.swing.JPasswordField pin;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
