/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.util.Date;
import java.sql.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author Zim
 */
public class signup extends javax.swing.JFrame {

    
int positionX = 0, positionY=0;


    public signup() {
        initComponents();
        dob.setDate(new Date());
        ques.add("What is your pet name ?");
        ques.add("What is your father name ?");
        ques.add("What is your favourite sports ?");
        ques.add("What is your favourite book name ?");
        ques.add("Where were you born ?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createb = new javax.swing.JButton();
        backb = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        actype = new javax.swing.JComboBox<>();
        lblun = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jobid = new javax.swing.JTextField();
        ad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        ques = new java.awt.Choice();
        lblpass2 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblpass3 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createb.setBackground(new java.awt.Color(204, 255, 255));
        createb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tatice-Cristal-Intense-Ok.24.png"))); // NOI18N
        createb.setText("Create");
        createb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createbMouseEntered(evt);
            }
        });
        createb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbActionPerformed(evt);
            }
        });
        jPanel1.add(createb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 90, 37));

        backb.setBackground(new java.awt.Color(204, 255, 255));
        backb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Graphicloads-100-Flat-2-Arrow-back.24.png"))); // NOI18N
        backb.setText("Back");
        backb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbActionPerformed(evt);
            }
        });
        jPanel1.add(backb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 78, 35));

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 272, 180, 30));

        un.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        un.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 222, 180, 30));

        actype.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        actype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin" }));
        actype.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        actype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actypeActionPerformed(evt);
            }
        });
        jPanel1.add(actype, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 100, -1));

        lblun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblun.setText("User Name:");
        jPanel1.add(lblun, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 25));

        lblname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblname.setText("Name:");
        jPanel1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        lblpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpass.setText("Answer:");
        jPanel1.add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 60, 30));

        lblat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblat.setText("Account Type :");
        jPanel1.add(lblat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Job ID: *");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, 30));

        jobid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jobid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jobid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 180, 30));

        ad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Hopstarter-Soft-Scraps-User-Executive-Green.64.png"))); // NOI18N
        ad.setText("  Account Details");
        jPanel1.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 220, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("  X");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 30, 30));

        password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 180, 30));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Light-Eye-off.32.png"))); // NOI18N
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel1.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 30, 30));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Custom-Icon-Design-Pretty-Office-8-Eye.32.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        lblpass1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpass1.setText("Date Of Birth:");
        jPanel1.add(lblpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 100, 30));

        ques.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 280, 30));

        lblpass2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpass2.setText("Security Question:");
        jPanel1.add(lblpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 130, 30));

        ans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ans.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ansKeyPressed(evt);
            }
        });
        jPanel1.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/6159448.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 430, 360));

        lblpass3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpass3.setText("Password: ");
        jPanel1.add(lblpass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 80, 30));
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbActionPerformed
        String atype = (String) actype.getSelectedItem();
        String susername = un.getText();
        String sname = name.getText();
        String spassword = password.getText();
        String sjobid = jobid.getText();
        String sques = ques.getSelectedItem();
        String sans = ans.getText();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String sdate = df.format(dob.getDate());
        

        try {
            Conn c = new Conn();
                
                   String query1 = "select * from adminlogin where jobid = '"+sjobid+"'  ";
                   ResultSet rs = c.s.executeQuery(query1);
                
                   if (sname.equals("") || sjobid.equals("") || susername.equals("") || 
                        spassword.equals("") || sques.equals("") || 
                        sans.equals("")){
                      JOptionPane.showMessageDialog(null, "All informations Are Required!!");
                       
                   }else if(!isInteger(sjobid)){
                       JOptionPane.showMessageDialog(null, "Please Enter the Job ID in Integer format!!");
                   
                   }else if(!isValidUsername(susername)){
                JOptionPane.showMessageDialog(null, "Username should only contain combination of alphabetic characters and numbers!!");
               
            }
                       else if(rs.next()){
                        
                          String  query2 = "update adminlogin set username = '"+susername+"', name = '"+sname+"', PASSWORD = '"+spassword+"', date_of_birth = '"+sdate+"', account_type = '"+atype+"', Security_Question = '"+sques+"', answer= '"+sans+"' where jobid = '"+sjobid+"'";
                        c.s.executeUpdate(query2);
                        JOptionPane.showMessageDialog(null, "Account Created Successfully");
                        setVisible(false);
                new Login().setVisible(true);
        }
            else {
                       JOptionPane.showMessageDialog(null, "Job ID Cannot Found!!!");
                un.setText("");
                password.setText("");
                name.setText("");
                jobid.setText("");
                ans.setText("");
                   }
                  
                
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_createbActionPerformed

    private void actypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actypeActionPerformed

    }//GEN-LAST:event_actypeActionPerformed

    private void backbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_backbActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Do You want to Exit the Application?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
          System.exit(0);  
        }else{
            
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void createbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbMouseEntered
         
    }//GEN-LAST:event_createbMouseEntered

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
         password.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        password.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void ansKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ansKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String atype = (String) actype.getSelectedItem();
        String susername = un.getText();
        String sname = name.getText();
        String spassword = password.getText();
        String sjobid = jobid.getText();
        String sques = ques.getSelectedItem();
        String sans = ans.getText();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String sdate = df.format(dob.getDate());
        

        try {
            Conn c = new Conn();
                
                   String query1 = "select * from adminlogin where jobid = '"+sjobid+"'  ";
                   ResultSet rs = c.s.executeQuery(query1);
                
                   if (sname.equals("") || sjobid.equals("") || susername.equals("") || 
                        spassword.equals("") || sques.equals("") || 
                        sans.equals("")){
                      JOptionPane.showMessageDialog(null, "All informations Are Required!!");
                       
                   }else if(!isInteger(sjobid)){
                       JOptionPane.showMessageDialog(null, "Please Enter the Job ID in Integer format!!");
                   
                   }else if(!isValidUsername(susername)){
                JOptionPane.showMessageDialog(null, "Username should only contain combination of alphabetic characters and numbers!!");
               
            }else if(!isChar(sname)){
            
            JOptionPane.showMessageDialog(null, "Enter Username in Character Format!!");
            
            }else if(rs.next()){
                        
                          String  query2 = "update adminlogin set username = '"+susername+"', name = '"+sname+"', PASSWORD = '"+spassword+"', date_of_birth = '"+sdate+"', account_type = '"+atype+"', Security_Question = '"+sques+"', answer= '"+sans+"' where jobid = '"+sjobid+"'";
                        c.s.executeUpdate(query2);
                        JOptionPane.showMessageDialog(null, "Account Created Successfully");
                        setVisible(false);
                new Login().setVisible(true);
        }
            else {
                       JOptionPane.showMessageDialog(null, "Job ID Cannot Found!!!");
                un.setText("");
                password.setText("");
                name.setText("");
                jobid.setText("");
                ans.setText("");
                   }
                  
                
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_ansKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        positionX = evt.getX();
        positionY = evt.getY();


    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_formMouseDragged

     public static boolean isValidUsername(String username) {
        
        return username.matches("^[a-zA-Z0-9]*$");
    }
  
    
   public static boolean isInteger(String str) {
        
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public static boolean isChar(String cha) {
        
       for (int i = 0; i < cha.length(); i++) {
        if (!Character.isLetter(cha.charAt(i))) {
            return false;
        }
    }
    return true;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> actype;
    private javax.swing.JLabel ad;
    private javax.swing.JTextField ans;
    private javax.swing.JButton backb;
    private javax.swing.JButton createb;
    private javax.swing.JLabel disable;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jobid;
    private javax.swing.JLabel lblat;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblpass2;
    private javax.swing.JLabel lblpass3;
    private javax.swing.JLabel lblun;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private java.awt.Choice ques;
    private javax.swing.JLabel show;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
