/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author Zim
 */
public class updateinfo extends javax.swing.JFrame {

    
    
int positionX = 0, positionY=0;



    public updateinfo() {
        

        
        initComponents();
    }
        
     public updateinfo(String smeter) {

        initComponents();
        
        meterno.setText(smeter);
        
        String ameter = meterno.getText();

        try{

            Conn c = new Conn();
            String query = "select * from customer where meter_no = '"+ameter+"'";
            ResultSet rs = c.s.executeQuery(query);

            while (rs.next()){

                cname.setText(rs.getString("name"));
                
                phone.setText(rs.getString("phone"));
                email.setText(rs.getString("email"));

            }

        }catch (Exception e){
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        csname = new javax.swing.JTextField();
        csemail = new javax.swing.JTextField();
        csphone = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        meterno = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Antialiasfactory-Enterprise-Resource-Planning-Balance.24.png"))); // NOI18N
        jLabel2.setText(" Update Your Information");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 460, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Meter No:");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name:");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone:");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 50, 30));

        cname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 190, 30));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, 30));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TO:");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 40, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TO:");
        panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 30, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("TO:");
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 30, 30));
        panel.add(csname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 200, 30));
        panel.add(csemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 200, 30));

        csphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                csphoneKeyPressed(evt);
            }
        });
        panel.add(csphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 200, 30));

        back.setBackground(new java.awt.Color(204, 255, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Graphicloads-100-Flat-2-Arrow-back.24.png"))); // NOI18N
        back.setText("Cancel");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        panel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 110, 30));

        update.setBackground(new java.awt.Color(204, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tatice-Cristal-Intense-Ok.24.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        panel.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 120, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images.jpg"))); // NOI18N
        panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 270, 180));

        meterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel.add(meterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 140, 30));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText(" X");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        panel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 30, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Robinweatherall-Cleaning-Bubbles.256.png"))); // NOI18N
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 280, 290));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Custom-Icon-Design-Flatastic-6-Circle.256.png"))); // NOI18N
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -130, 290, 280));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Custom-Icon-Design-Flatastic-6-Circle.256.png"))); // NOI18N
        panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 360, 290, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        String smeter = meterno.getText();
        String sname = csname.getText();
        String semail = csemail.getText();
        String sphone = csphone.getText();
        

        try {
            Conn c = new Conn();

            

            
            if(sname.equals("") || sphone.equals("") || semail.equals("")){
                   
                JOptionPane.showMessageDialog(null, "Information Fields Cannot Be Empty!!");
            }
            else {
                String  query2 = "update customer set name = '"+sname+"', email = '"+semail+"', phone = '"+sphone+"' where meter_no = '"+smeter+"'";
                c.s.executeUpdate(query2);
                JOptionPane.showMessageDialog(null, "Account Updated Successfully");
                
                
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
               
        setVisible(false);
        
    }//GEN-LAST:event_backActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Do You want to Exit the Application?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
          System.exit(0);  
        }else{
            
        }
    }//GEN-LAST:event_exitMouseClicked

    private void csphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csphoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
             String smeter = meterno.getText();
        String sname = csname.getText();
        String semail = csemail.getText();
        String sphone = csphone.getText();
        

        try {
            Conn c = new Conn();

            

            
            if(sname.equals("") || sphone.equals("") || semail.equals("")){
                   
                JOptionPane.showMessageDialog(null, "Information Fields Cannot Be Empty!!");
            }
            else {
                String  query2 = "update customer set name = '"+sname+"', email = '"+semail+"', phone = '"+sphone+"' where meter_no = '"+smeter+"'";
                c.s.executeUpdate(query2);
                JOptionPane.showMessageDialog(null, "Account Updated Successfully");
                
                
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_csphoneKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        positionX = evt.getX();
        positionY = evt.getY();


    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateinfo("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel cname;
    private javax.swing.JTextField csemail;
    private javax.swing.JTextField csname;
    private javax.swing.JTextField csphone;
    private javax.swing.JLabel email;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel meterno;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel phone;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private String getText(String smeter) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
