/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Zim
 */
public class UpdatecustomerInfo extends javax.swing.JFrame {

    
int positionX = 0, positionY=0;


    public UpdatecustomerInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        meterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        check = new javax.swing.JButton();
        cname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        nid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        csname = new javax.swing.JTextField();
        csemail = new javax.swing.JTextField();
        csnid = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        csphone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        csaddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cscity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Hopstarter-Soft-Scraps-Text-Edit.24.png"))); // NOI18N
        jLabel2.setText(" Update Customer Information");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 530, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Meter No\\Phone No:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 30));

        meterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meternoActionPerformed(evt);
            }
        });
        meterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                meternoKeyPressed(evt);
            }
        });
        jPanel2.add(meterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 60, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NID:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 70, 30));

        check.setBackground(new java.awt.Color(204, 255, 255));
        check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Google-Noto-Emoji-Smileys-10024-thinking-face.24.png"))); // NOI18N
        check.setText("Check");
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkMouseEntered(evt);
            }
        });
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel2.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 120, 30));

        cname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, 30));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, 30));

        nid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 150, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TO:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 40, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TO:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 30, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("TO:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 30, 30));
        jPanel2.add(csname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 170, 30));
        jPanel2.add(csemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, 30));
        jPanel2.add(csnid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 170, 30));

        back.setBackground(new java.awt.Color(204, 255, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Graphicloads-100-Flat-2-Arrow-back.24.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 100, 30));

        update.setBackground(new java.awt.Color(204, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tatice-Cristal-Intense-Ok.24.png"))); // NOI18N
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 130, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images.jpg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 250, 180));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Phone:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 50, 30));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 160, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("TO:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 30, 30));
        jPanel2.add(csphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 170, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Address:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 70, 30));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 160, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("TO:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 30, 30));
        jPanel2.add(csaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 170, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("City:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 70, 30));

        city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 160, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("TO:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 30, 30));
        jPanel2.add(cscity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 170, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText(" X");
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 30, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Custom-Icon-Design-Flatastic-6-Circle.256.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -140, 310, 290));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Robinweatherall-Cleaning-Bubbles.256.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 310, 320));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Custom-Icon-Design-Flatastic-6-Circle.256.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, -60, 260, 300));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void meternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meternoActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        String smeter = meterno.getText();
        
        try{
                
                Conn c = new Conn();
                    String query = "select * from customer where meter_no = '"+smeter+"' or phone = '"+smeter+"'";
                    ResultSet rs = c.s.executeQuery(query);
                
                
                if (rs.next()){
                     
                cname.setText(rs.getString("name"));
                
                phone.setText(rs.getString("phone"));
                email.setText(rs.getString("email"));
                address.setText(rs.getString("address"));
                city.setText(rs.getString("city"));
                nid.setText(rs.getString("nid"));
            
                   
                }else if (smeter.equals("")) {
                
                JOptionPane.showMessageDialog(null, "Meter No/Phone No Field Cannot Be Empty!!");
            }
            else {
                JOptionPane.showMessageDialog(null, "Meter No/Phone No Cannot Found!!");
                meterno.setText("");
                
            }
                
   
               
            }catch (Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_checkActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String smeter = meterno.getText();
        String sname = csname.getText();
        String semail = csemail.getText();
        String sphone = csphone.getText();
        
        String saddress = csaddress.getText();
        String scity = cscity.getText();
        String snid = csnid.getText();
        
        try {
            Conn c = new Conn();
                
                   
                
                   if (smeter.equals("") || sname.equals("") || semail.equals("") || 
                        sphone.equals("") || saddress.equals("") || scity.equals("") || 
                        snid.equals("")){
                      
                     JOptionPane.showMessageDialog(null, "All Fields are Required!!");
                       
                   }
                    
                       else{
                           String  query2 = "update customer set name = '"+sname+"', email = '"+semail+"', phone = '"+sphone+"', address = '"+saddress+"', city = '"+scity+"', nid = '"+snid+"' where meter_no = '"+smeter+"'";
                        c.s.executeUpdate(query2);
                        JOptionPane.showMessageDialog(null, "Account Updated Successfully");
                         
                       }
                  
                
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        
    }//GEN-LAST:event_backActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Do You want to Exit the Application?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
          System.exit(0);  
        }else{
            
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void checkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseEntered
         String smeter = meterno.getText();
        if (smeter.equals("")){
            check.setEnabled(false);
        }else{
            check.setEnabled(true);
        }
    }//GEN-LAST:event_checkMouseEntered

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        
         String smeter = meterno.getText();
        String sname = csname.getText();
        String semail = csemail.getText();
        String sphone = csphone.getText();
        
        String saddress = csaddress.getText();
        String scity = cscity.getText();
        String snid = csnid.getText();
        
        if (smeter.equals("") || sname.equals("") || semail.equals("") || 
                        sphone.equals("") ||  saddress.equals("") || 
                        scity.equals("") || snid.equals("")){
            update.setEnabled(false);
        }else{
            update.setEnabled(true);
        }
    }//GEN-LAST:event_updateMouseEntered

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        positionX = evt.getX();
        positionY = evt.getY();


    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_formMouseDragged

    private void meternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meternoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
             String smeter = meterno.getText();
        String sname = csname.getText();
        String semail = csemail.getText();
        String sphone = csphone.getText();
        
        String saddress = csaddress.getText();
        String scity = cscity.getText();
        String snid = csnid.getText();
        
        try {
            Conn c = new Conn();
                
                   
                
                   if (smeter.equals("") || sname.equals("") || semail.equals("") || 
                        sphone.equals("") || saddress.equals("") || scity.equals("") || 
                        snid.equals("")){
                      
                     JOptionPane.showMessageDialog(null, "All Fields are Required!!");
                       
                   }
                    
                       else{
                           String  query2 = "update customer set name = '"+sname+"', email = '"+semail+"', phone = '"+sphone+"', address = '"+saddress+"', city = '"+scity+"', nid = '"+snid+"' where meter_no = '"+smeter+"'";
                        c.s.executeUpdate(query2);
                        JOptionPane.showMessageDialog(null, "Account Updated Successfully");
                         
                       }
                  
                
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_meternoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatecustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatecustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatecustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatecustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatecustomerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JButton back;
    private javax.swing.JButton check;
    private javax.swing.JLabel city;
    private javax.swing.JLabel cname;
    private javax.swing.JTextField csaddress;
    private javax.swing.JTextField cscity;
    private javax.swing.JTextField csemail;
    private javax.swing.JTextField csname;
    private javax.swing.JTextField csnid;
    private javax.swing.JTextField csphone;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField meterno;
    private javax.swing.JLabel nid;
    private javax.swing.JLabel phone;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
